/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Familias;


import clases.MetodosFamilia;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class frmfamiliaBuscar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmArticulosBuscar
     */
    public static  DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
    public static DefaultTableModel modelotablafamilia = new DefaultTableModel(){
           @Override
           public boolean isCellEditable(int filas, int columnas) {
            return false;   
           }
       };
    public static int  contador=0;// Variable que hace que no se duplique el jframe de editar articulos
    public static int  inicializador ;//variable para saber si es buscar o editar
     MetodosFamilia met = new MetodosFamilia(); 
    frmFamiliaEditar editar2;
    Dimension desktopSize;
    Dimension FrameSize;
    public frmfamiliaBuscar()  
    {
        initComponents();
        dobleclick();
    }
    
    
//    public void bloquear(){
//        for( Component a: pnlBuscarArticulos.getComponents()){
//            a.setEnabled(false);
//        }
//    }
//     public void desbloquear(){
//        for( Component a: pnlBuscarArticulos.getComponents()){
//            a.setEnabled(true);
//        }
//    }
    
    void dobleclick()
    {
        tblfamilabuscar.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent Mouse_evt){
            if(Mouse_evt.getClickCount()==2){
               
                if(inicializador==2)//Abrir Editar
                {    if(contador>=1)//No abre dos veces el formulario frmClientes Editar.
                    {
                    }
                    else
                    {//abra el formulario de editar.
                      enviardatos();
//                      bloquear();
                      
                    }
                }
                
                else if(inicializador==3)
                {
                    
                }
                else
                {
                    //No ejecuta el doble clic
                }
            }  
        }
        });
    }
    
    public void enviardatos()
    {
        
        frmFamiliaEditar editar;
        editar = new frmFamiliaEditar();
        frmfamilia.panel1.add(editar);
        desktopSize = frmfamilia.panel1.getSize();
        FrameSize = editar.getSize();
        editar.setLocation((desktopSize.width - FrameSize.width)/1, (desktopSize.height- FrameSize.height)/10);
        this.setClosable(false) ;
        editar.show();
        contador=contador+1;
        met.FamiliaEditarPasar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscarArticulos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfamiliabuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfamilabuscar = new javax.swing.JTable();
        lblregresar = new javax.swing.JLabel();

        jLabel1.setText("Nombre:");

        txtfamiliabuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfamiliabuscarKeyTyped(evt);
            }
        });

        tblfamilabuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblfamilabuscar);

        lblregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        lblregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarArticulosLayout = new javax.swing.GroupLayout(pnlBuscarArticulos);
        pnlBuscarArticulos.setLayout(pnlBuscarArticulosLayout);
        pnlBuscarArticulosLayout.setHorizontalGroup(
            pnlBuscarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarArticulosLayout.createSequentialGroup()
                .addGroup(pnlBuscarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarArticulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblregresar))
                    .addGroup(pnlBuscarArticulosLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtfamiliabuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarArticulosLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnlBuscarArticulosLayout.setVerticalGroup(
            pnlBuscarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBuscarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfamiliabuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBuscarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBuscarArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblregresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregresarMouseClicked
        // TODO add your handling code here
         //met.limpiartabla();
         modelotablafamilia.setRowCount(0);
         this.dispose();
         met.mostrarbotones();
       
    }//GEN-LAST:event_lblregresarMouseClicked

    private void txtfamiliabuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfamiliabuscarKeyTyped
        // TODO add your handling code here:
        String articulo;
        articulo = txtfamiliabuscar.getText();
        met.buscartabla(articulo);
        
    }//GEN-LAST:event_txtfamiliabuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblregresar;
    private javax.swing.JPanel pnlBuscarArticulos;
    public static javax.swing.JTable tblfamilabuscar;
    public static javax.swing.JTextField txtfamiliabuscar;
    // End of variables declaration//GEN-END:variables
}
