/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import clases.MetodosClientes;
import clases.MetodosVentas;
import clases.modalInternalFrame;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public final class frmClientesBuscar extends modalInternalFrame {

    /**
     * Creates new form frmClientesBuscar
     */
    public static DefaultTableModel tablaBuscar = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int filas, int columnas) {
            return false;
        }

    };
    MetodosClientes met = new MetodosClientes();/// inicializa la clase de metodos
    MetodosVentas metventas = new MetodosVentas();
    frmClientesEditar editar = new frmClientesEditar();
    Dimension desktopSize;
    Dimension FrameSize;
    public static int contador = 0;// Variable que hace que no se duplique el jframe de editar clientes
    public static int inicializador;//variable para saber si es buscar o editar

    public frmClientesBuscar() {
        initComponents();
        click();
    }

    void click() {
        tblClientesBuscar.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                if (Mouse_evt.getClickCount() == 2) {

                    if (inicializador == 2)//Abrir Editar
                    {
                        if (contador >= 1)//No abre dos veces el formulario frmClientes Editar.
                        {
                        } else {//abra el formulario de editar.
                            enviardatos();
                            met.buscarclientetabla("");
                        }
                    } else if (inicializador == 3) {
                        metventas.regresarCliente();
                        cerrar();//cierra este interna
                    } else {

                        //No ejecuta el doble clic
                    }
                }
            }
        });
    }

    public void cerrar() {
        this.dispose();
        tablaBuscar.setRowCount(0);
    }

    void enviardatos() {

        frmClientes.panel1.add(editar);
        desktopSize = frmClientes.panel1.getSize();
        FrameSize = editar.getSize();
        editar.setLocation((desktopSize.width - FrameSize.width) / 1, (desktopSize.height - FrameSize.height) / 120);
        editar.show();
        contador = contador + 1;
        met.ClientesEditarPasar();
        txtClientesBuscar.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClientesBuscar = new javax.swing.JTextField();
        btnregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientesBuscar = new javax.swing.JTable();

        jLabel1.setText("Nombre");

        txtClientesBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientesBuscarActionPerformed(evt);
            }
        });
        txtClientesBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClientesBuscarKeyReleased(evt);
            }
        });

        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        tblClientesBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblClientesBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txtClientesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnregresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClientesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientesBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientesBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientesBuscarActionPerformed

    private void txtClientesBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientesBuscarKeyReleased
        // TODO add your handling code here:
        String cliente;
        cliente = txtClientesBuscar.getText();
        met.buscarclientetabla(cliente);
    }//GEN-LAST:event_txtClientesBuscarKeyReleased

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        if (inicializador == 3) {
            this.dispose();
            met.limpiartablaclientesbuscarclientes();
        } else {
            frmClientes.valor = 1;
            this.dispose();
            met.mostrarbbotones();
            met.buscarclientetabla("");
            met.limpiartablaclientesbuscarclientes();
        }

    }//GEN-LAST:event_btnregresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblClientesBuscar;
    public static javax.swing.JTextField txtClientesBuscar;
    // End of variables declaration//GEN-END:variables
}
