/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import clases.Metodos;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author usuario
 */
public final class frmClientesBuscar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmClientesBuscar
     */
    public static DefaultTableModel tablaBuscar = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas) {
         return false;   
        }
        
    };
     Metodos met= new Metodos();/// inicializa la clase de metodos
    
     Dimension desktopSize;
     Dimension FrameSize;
     
     public static int  contador=0;// Variable que hace que no se duplique el jframe de editar clientes
     
    
     public frmClientesBuscar() {
     initComponents();
     ModeloTabla();
     met.BuscarClientes();
     click();
     
      
    }
     
  public  void ModeloTabla(){
   
    tablaBuscar.addColumn("N°cliente");
    tablaBuscar.addColumn("Nombre");
    tablaBuscar.addColumn("Telefono");
    tablaBuscar.addColumn("Pago");
    tablaBuscar.addColumn("Días");
    tablaBuscar.addColumn("Colonia");
    tablaBuscar.addColumn("Calle");
    tablaBuscar.addColumn("# Exterior");
    tablaBuscar.addColumn("# Interior");
    tablaBuscar.addColumn("CP");
    tblClientesBuscar.setModel(tablaBuscar);
    TableColumnModel ModeloColumnas = tblClientesBuscar.getColumnModel();
    ModeloColumnas.getColumn(0).setPreferredWidth(70);
    ModeloColumnas.getColumn(1).setPreferredWidth(230);
    ModeloColumnas.getColumn(2).setPreferredWidth(90);
    ModeloColumnas.getColumn(3).setPreferredWidth(40);
    ModeloColumnas.getColumn(4).setPreferredWidth(40);
    ModeloColumnas.getColumn(5).setPreferredWidth(120);
    ModeloColumnas.getColumn(6).setPreferredWidth(120);
    ModeloColumnas.getColumn(7).setPreferredWidth(70);
    ModeloColumnas.getColumn(8).setPreferredWidth(70);
    ModeloColumnas.getColumn(9).setPreferredWidth(50);
  
    }
    
         
    void click()
    {
        tblClientesBuscar.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent Mouse_evt){
            if(Mouse_evt.getClickCount()==2){
                enviardatos();
                met.buscarclientetabla("");
            }  
        }
        });
    }
    
   
    void enviardatos()
    {
        frmClientesEditar editar = new frmClientesEditar();
        frmClientes.panel1.add(editar);
        desktopSize = frmClientes.panel1.getSize();
        FrameSize = editar.getSize();
        editar.setLocation((desktopSize.width - FrameSize.width)/1, (desktopSize.height- FrameSize.height)/120);
        editar.show();
        contador=contador+1;
        met.ClientesEditarPasar();
        txtClientesBuscar.setText("");
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClientesBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientesBuscar = new javax.swing.JTable();

        jLabel1.setText("Nombre");

        txtClientesBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientesBuscarActionPerformed(evt);
            }
        });
        txtClientesBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClientesBuscarKeyReleased(evt);
            }
        });

        tblClientesBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblClientesBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClientesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientesBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientesBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientesBuscarActionPerformed

    private void txtClientesBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientesBuscarKeyReleased
        // TODO add your handling code here:
        String cliente;
        cliente=txtClientesBuscar.getText();
       met.buscarclientetabla(cliente);
    }//GEN-LAST:event_txtClientesBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblClientesBuscar;
    public static javax.swing.JTextField txtClientesBuscar;
    // End of variables declaration//GEN-END:variables
}
