/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proveedores;

import Compras.frmComprasnuevas;
import clases.MetodosCompras;
import clases.MetodosProveedores;
import clases.modalInternalFrame;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class frmProveedorBuscar extends modalInternalFrame {

    /**
     * Creates new form frmProveedorBuscar
     */
    public static DefaultTableModel modeloTabla = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas) {
         return false;   
        }
        
    };
    public static  DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
    MetodosProveedores met= new MetodosProveedores();
    MetodosCompras metcompras= new MetodosCompras();
    public static int contador =0;
    public static int inicializador=0;
     Dimension desktopSize;
    Dimension FrameSize;
    public frmProveedorBuscar() {
        initComponents();
        click();
    }

    public frmProveedorBuscar(frmComprasnuevas aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    void click()
    {
        tblBuscar.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent Mouse_evt){
            if(Mouse_evt.getClickCount()==2){
               
                if(inicializador==2)//Abrir Editar
                {    if(contador>=1)//No abre dos veces el formulario frmClientes Editar.
                    {
                    }
                
                    
                    else
                    {//abra el formulario de editar.
                         enviar();
//                        met.buscarclientetabla("");
                    }
                }
                else if(inicializador==3){ //Manda datos al formulario de Compras
                    metcompras.regresarproveedor();
                    cerrar();//cierra este interna
                }
                else
                {
                    //No ejecuta el doble clic
                }
            }  
        }
        });
    }
    public void cerrar(){
        this.dispose();
        modeloTabla.setRowCount(0);
    }
    public void enviar(){
        frmProveedorEditar edi= new frmProveedorEditar();
        frmProveedores.panel2.add(edi);
        desktopSize = frmProveedores.panel2.getSize();
        FrameSize = edi.getSize();
        edi.setLocation((desktopSize.width - FrameSize.width)/1, (desktopSize.height- FrameSize.height)/120);
        edi.show();
        contador=1;
      
//        lblRegresar.setEnabled(false);
        met.enviardatos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscar = new javax.swing.JTable();
        lblRegresar = new javax.swing.JLabel();

        jLabel1.setText("Nombre");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        tblBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBuscar);

        lblRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        lblRegresar.setToolTipText("");
        lblRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegresarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRegresar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
        // TODO add your handling code here:
       if(inicializador==3)
       {
           String fechapago = frmComprasnuevas.lblFechaPago.getText();
           
       }
       else
       {
            met.mostrarbotones();
       }
       
        frmProveedorBuscar.modeloTabla.setRowCount(0);
        this.dispose();
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
         String proveedor;
         proveedor=txtBuscar.getText().trim();
         System.out.println(proveedor);
        met.filtrarDatosTableBuscar(proveedor);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void lblRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMousePressed
        // TODO add your handling code here:
//        frmProveedorBuscar.modeloTabla.setRowCount(0);
//        this.dispose();
    }//GEN-LAST:event_lblRegresarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegresar;
    public static javax.swing.JTable tblBuscar;
    public static javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
